"""empty message

Revision ID: e0623781ff6c
Revises: 356c6e4f3f47
Create Date: 2020-06-08 15:58:13.375110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0623781ff6c'
down_revision = '356c6e4f3f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('colors', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=False),
    sa.Column('filename_1', sa.String(length=80), nullable=True),
    sa.Column('image_2', sa.String(length=150), nullable=False),
    sa.Column('filename_2', sa.String(length=80), nullable=True),
    sa.Column('image_3', sa.String(length=150), nullable=False),
    sa.Column('filename_3', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('addproduct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addproduct',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('colors', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pub_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_1', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('filename_1', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('image_2', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('filename_2', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('image_3', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('filename_3', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='addproduct_brand_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='addproduct_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='addproduct_pkey'),
    sa.UniqueConstraint('slug', name='addproduct_slug_key')
    )
    op.drop_table('product')
    # ### end Alembic commands ###
